### ISSUE TITLE
Review #1 - La page queda en blanco al recargar.

### ISSUE THREAD

**Issue by FacundoEG** [Lio-n/dwf-m6-desafio#1]
Hola Lion! como estas? te comento que estuve probando un poco la webapp y la verdad que la veo funcionando muy bien! se puede jugar muy fluidamente y las animaciones te quedaron muy buenas.

La unica cosita, a modo de detalle que encontre es que cuando vos recargas la pagina no te permite hacer mas nada luego porque sale esta pantalla:

![Screenshot_20220107_110646](https://user-images.githubusercontent.com/79592789/148555296-ca14a341-b6bf-41fd-bd03-cce94d1e40db.png)

Te recomendaría si queres darle una vuelta de rosca, que revises el render de la page, ya que la pagina te la vuelve a recargar en la misma posición pero al parecer hay un problema con un request para poder volver a ingresar.

De todas formas te lo comento a modo de detalle, en lineas generales lo veo re bien optimizado al juego y cumple con las premisas del desafío!

Asi que de mi parte te mando saludos y te deseo exitos para el proximo modulo!

**Comment by Lio-n** [comment]
Hola @FacundoEG , Muchas Gracias por el feedback!

Estuve viendo eso, y es raro por que en 'development' todo funciona correctamente.
No creo que sea problema con el render de la page, creo que es un problema relacionado con el path.

Pero bue, me fijo como lo arreglo.
Thx!

**Comment by WASD6570** [comment]
Hola @Lio-n mismo inconveniente que facu

**Comment by Lio-n** [comment]
Buenas!
Ya lo arregle, ahora todo debería funcionar correctamente 🤙.
